/** @format */

export const TEXTS = {
	en: {
		settings: {
			title: 'Trivia Challenge',
			subtitle: 'Select settings and start the quiz!',
			category: 'Category',
			difficulty: 'Difficulty',
			questionCount: 'Number of Questions',
			questionType: 'Question Type',
			startButton: 'Start Quiz',
			anyCategory: 'Any Category',
			anyDifficulty: 'Any Difficulty',
			multipleChoice: 'Multiple Choice',
			trueFalse: 'True / False',
			questions: 'Questions',
			language: 'Language',
			english: 'English',
			turkish: 'Turkish',
			errors: {
				notEnoughQuestions:
					'Not enough questions available for these criteria',
				failedToLoadCategories:
					'Failed to load categories. Please try again.',
				failedToLoadQuestions:
					'Failed to load questions. Please try again.',
				networkError: 'Network error. Please check your connection.',
				serverError: 'Server error. Please try again later.',
			},
		},
		categories: {
			'General Knowledge': 'General Knowledge',
			'Science & Nature': 'Science & Nature',
			'Entertainment: Books': 'Entertainment: Books',
			'Entertainment: Film': 'Entertainment: Film',
			'Entertainment: Music': 'Entertainment: Music',
			'Entertainment: Television': 'Entertainment: Television',
			'Entertainment: Video Games': 'Entertainment: Video Games',
			'Entertainment: Board Games': 'Entertainment: Board Games',
			'Science: Computers': 'Science: Computers',
			'Science: Mathematics': 'Science: Mathematics',
			'Science: Gadgets': 'Science: Gadgets',
			Mythology: 'Mythology',
			Sports: 'Sports',
			Geography: 'Geography',
			History: 'History',
			Politics: 'Politics',
			Art: 'Art',
			Celebrities: 'Celebrities',
			Animals: 'Animals',
			Vehicles: 'Vehicles',
			Comics: 'Comics',
			'Anime: Manga': 'Anime: Manga',
			Cartoon: 'Cartoon',
		},
		difficulty: {
			EASY: 'EASY',
			MEDIUM: 'MEDIUM',
			HARD: 'HARD',
		},
		feedback: {
			correct: 'Correct! 🎉',
			incorrect: 'Incorrect! 😔',
			correctAnswer: 'Correct answer:',
			tryAgain: 'Try Again',
			nextQuestion: 'Next Question',
			timeLeft: 'Time Left',
			seconds: 'seconds',
		},
		game: {
			question: 'Question',
			restart: 'Restart',
			correct: 'Correct',
			incorrect: 'Incorrect',
			score: 'Score',
			complete: 'Quiz Complete!',
			playAgain: 'Play Again',
			loading: 'Loading...',
			questionsLeft: 'Questions Left',
			totalQuestions: 'Total Questions',
			category: 'Category',
			difficulty: 'Difficulty',
		},
		score: {
			excellent: "🏆 Excellent! You're a trivia master!",
			good: '🌟 Good job! Keep practicing!',
			needsImprovement: "💪 Don't give up! Try again!",
		},
	},
	tr: {
		settings: {
			title: 'Bilgi Yarışması',
			subtitle: 'Ayarları seçin ve yarışmaya başlayın!',
			category: 'Kategori',
			difficulty: 'Zorluk',
			questionCount: 'Soru Sayısı',
			questionType: 'Soru Tipi',
			startButton: 'Yarışmayı Başlat',
			anyCategory: 'Tüm Kategoriler',
			anyDifficulty: 'Tüm Zorluk Seviyeleri',
			multipleChoice: 'Çoktan Seçmeli',
			trueFalse: 'Doğru/Yanlış',
			questions: 'Soru',
			language: 'Dil',
			english: 'İngilizce',
			turkish: 'Türkçe',
			errors: {
				notEnoughQuestions:
					'Bu kriterler için yeterli soru bulunmamaktadır',
				failedToLoadCategories:
					'Kategoriler yüklenemedi. Lütfen tekrar deneyin.',
				failedToLoadQuestions:
					'Sorular yüklenemedi. Lütfen tekrar deneyin.',
				networkError:
					'Bağlantı hatası. Lütfen internet bağlantınızı kontrol edin.',
				serverError: 'Sunucu hatası. Lütfen daha sonra tekrar deneyin.',
			},
		},
		categories: {
			'General Knowledge': 'Genel Kültür',
			'Science & Nature': 'Bilim & Doğa',
			'Entertainment: Books': 'Eğlence: Kitaplar',
			'Entertainment: Film': 'Eğlence: Film',
			'Entertainment: Music': 'Eğlence: Müzik',
			'Entertainment: Television': 'Eğlence: Televizyon',
			'Entertainment: Video Games': 'Eğlence: Video Oyunları',
			'Entertainment: Board Games': 'Eğlence: Masa Oyunları',
			'Science: Computers': 'Bilim: Bilgisayarlar',
			'Science: Mathematics': 'Bilim: Matematik',
			'Science: Gadgets': 'Bilim: Teknolojik Aletler',
			Mythology: 'Mitoloji',
			Sports: 'Spor',
			Geography: 'Coğrafya',
			History: 'Tarih',
			Politics: 'Politika',
			Art: 'Sanat',
			Celebrities: 'Ünlüler',
			Animals: 'Hayvanlar',
			Vehicles: 'Araçlar',
			Comics: 'Çizgi Romanlar',
			'Anime: Manga': 'Anime: Manga',
			Cartoon: 'Çizgi Film',
		},
		difficulty: {
			EASY: 'KOLAY',
			MEDIUM: 'ORTA',
			HARD: 'ZOR',
		},
		feedback: {
			correct: 'Doğru! 🎉',
			incorrect: 'Yanlış! 😔',
			correctAnswer: 'Doğru cevap:',
			tryAgain: 'Tekrar Dene',
			nextQuestion: 'Sonraki Soru',
			timeLeft: 'Kalan Süre',
			seconds: 'saniye',
		},
		game: {
			question: 'Soru',
			restart: 'Yeniden Başlat',
			correct: 'Doğru',
			incorrect: 'Yanlış',
			score: 'Skor',
			complete: 'Yarışma Tamamlandı!',
			playAgain: 'Tekrar Oyna',
			loading: 'Yükleniyor...',
			questionsLeft: 'Kalan Soru',
			totalQuestions: 'Toplam Soru',
			category: 'Kategori',
			difficulty: 'Zorluk',
		},
		score: {
			excellent: '🏆 Mükemmel! Bir bilgi ustasısın!',
			good: '🌟 İyi iş! Pratik yapmaya devam et!',
			needsImprovement: '💪 Pes etme! Tekrar dene!',
		},
	},
};
